### ISSUE TITLE
Wordpress Calculations escaping Ampersands

### ISSUE THREAD

**Issue by ghost** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#10]
I have an issue where on some areas of my calculations, wordpress is escaping ampersands to &#038; which is breaking my form.  Doesn't look like the plugin is setup to stop the standard post escaping, so how can I resolve this issue please?

**Comment by ghost** [comment]
![2021-02-16_10-23-09](https://user-images.githubusercontent.com/79141177/108050030-fd9bdc00-7040-11eb-8829-e6123baad719.png)

**Comment by larangin** [comment]
hello, escape ampersands? that doestn look an settings of zigaform because in the additional javascript option. all the theme is black. probably that is not from zigaform. and that will depends on your wordpress site. I can have a look if you want, just email me the admin access at my mail info@softdiscover.com

**Comment by larangin** [comment]
since there is no replies. I will close this issue
