### ISSUE TITLE
question about "dyn radio btn"

### ISSUE THREAD

**Issue by pinky-ring** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#12]
I have question about "dyn radio btn." 
1)What is layout mode?
2)What is quantity mean?
3)If I chose label as "shown on hover." what happen when I see it with smartphone? Is label show if I tap the icon??
Any help will be appreciated!
Thank you in advance 😊

**Comment by larangin** [comment]
hello,
1) with layout mode, you can change the dynamic box to have different styles. 
one-> you can show a feature image as an option
two-> you can add three images, each image represent an state of checkbox. 
2) when you enable quantity, you can see an spinner above the image. e.g. you can put type of wines as option, then with quantity, you can select of number of wines of the selected option. 
3) good question. I didnt think about that, so I will not show it on smartphone. so you have to choose another option except "shown on hover"
let me know if you have any other question.

**Comment by pinky-ring** [comment]
Hello.
I understand all the answers you provided.
I was trying to get help in many places and no body replied to me except you.
I really appreciate your help. Thank you so much, larangrin!!

**Comment by lsoto6509** [comment]
How can we use the quantity in calculations? Where do I get the variable?

**Comment by larangin** [comment]
> How can we use the quantity in calculations? Where do I get the variable?

hello, for dynamic checkbox field, you can get the Field price or Option price. in the calculation. if you want to get the quantity, just add a conditional like this. 

var quantityOption1=0;
if(fld_ui1pp0rgikl_optIsChecked_0){
  var pricePerUnit=4;
  quantityOption1=fld_ui1pp0rgikl_optprice_0/pricePerUnit;
}

in summary, you check if the option is checked, then you divide option price by price per unit which is a constant that you defined on field options. 

let me know if you have any questions.

**Comment by lsoto6509** [comment]
Hello, and thank you for your reply.

I am not setting a price in the dynamic radio button because the price will vary depending on QUANTITY from the spinner. The quantity represents the NUMBER OF USERS, and the price will change if the amount is 1,  between 2 and 99, or 100 to 399. I don’t see how I can calculate the quantity based on the code that you suggest.

I noticed that in the Option > Variables > Backend, you refer to this quantity, but it is not present in the front end, or in the variable available in the calculation panel.

***@***.***D73F34.FA3DEA90]

My question is, how can I get the value of the quantity (without depending on any other variables), to use that in my calculation?

Thanks in advance,

***@***.***D73F34.FA3DEA90]<https://www.sotonets.com/>

[Title: LinkedIn - Description: image of LinkedIn icon]<https://www.linkedin.com/company/sotonets/>[Title: Facebook - Description: image of Facebook icon]<https://www.facebook.com/sotonets/> [Title: Twitter - Description: image of Twitter icon] <https://twitter.com/sotonets>
Leonardo Soto
President at SotoNets Cloud Solutions

Email: ***@***.******@***.***>
Phone: (587)333-6691 (voice | text | fax)

#2500, 500 4th Ave. SW, Calgary, AB T2P-2V6
www.sotonets.com<http://www.sotonets.com/> | Book a time with ***@***.***/bookings/s/uIhVVpxtxEeR5_JqLY29MQ2>

***@***.***D73F34.FA3DEA90]<https://www.evolvebusinessalliance.ca/>
